### ISSUE TITLE
Security issue with urijs < 1.19.11 dependency

### ISSUE THREAD

**Issue by openam** [rse/hapi-plugin-websocket#19]
https://github.com/advisories/GHSA-3vjf-82ff-p4r3

![image](https://user-images.githubusercontent.com/419983/164316634-0e218aab-ee0a-4179-8c56-27207caffaec.png)

Is there a reason not to just use the `^` versions so all patches can be used?

**Comment by rse** [comment]
A new version exists. The ^ versions are nasty in practice as you cannot sure that 1.2.3 is really just a bugfix of 1.2.2 as not all NPM authors follow a strict semver versioning strategy.
